MVC2/CourseApp3/Models/ErrorViewModel.cs
namespace CourseApp3.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MVC2/CourseApp3/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CourseApp3.Models;

namespace CourseApp3.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MVC2/CourseApp3/Controllers/KursController.cs
using CourseApp3.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CourseApp3.Controllers
{
    public class KursController:Controller
    {
        private readonly DataContext _context;
        public KursController(DataContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var model = await _context.Kurslar.ToListAsync();
            return View(model);
        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Kurs model)
        {
            if(model == null)
            {
                return NotFound();
            }
            _context.Kurslar.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var model = await _context.Kurslar.FirstOrDefaultAsync(x=>x.KursId == id);
            if(model == null)
            {
                return NotFound();
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> edit(Kurs model)
        {
            if(model == null)
            {
                return NotFound();
            }
            if(ModelState.IsValid)
            {
                _context.Kurslar.Update(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var model = await _context.Kurslar.FirstOrDefaultAsync(x=>x.KursId == id);
            if(model == null)
            {
                return NotFound();
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]int KursId)
        {
            
            var model = await _context.Kurslar.FirstOrDefaultAsync(x=>x.KursId == KursId);
            if(model == null)
            {
                return NotFound();
            }
            _context.Kurslar.Remove(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

MVC2/CourseApp3/Controllers/KursKayitController.cs
using CourseApp3.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CourseApp3.Controllers
{
    public class KursKayitController:Controller
    {
        private readonly DataContext _context;
        public KursKayitController(DataContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var model = await _context.KursKayitlari
                                    .Include(x=>x.Ogrenci)
                                    .Include(k=>k.Kurs)
                                    .ToListAsync();
            return View(model);
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.Ogrenciler = new SelectList(await _context.Ogrenciler.ToListAsync(), "OgrenciId","AdSoyad");
            ViewBag.Kurslar = new SelectList(await _context.Kurslar.ToListAsync(), "KursId","KursBaslik");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(KursKayit model)
        {
            model.KayitTarihi = DateTime.Now;
            _context.KursKayitlari.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }
    }
}

MVC2/CourseApp3/Controllers/OgrenciController.cs
using CourseApp3.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CourseApp3.Controllers
{
    public class OgrenciController:Controller
    {
        private readonly DataContext _context;
        public OgrenciController(DataContext context)
        {
            _context = context;
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Ogrenci model)
        {
            if(model == null)
            {
                return NotFound();
            }
            if(ModelState.IsValid){
                _context.Ogrenciler.Add(model);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Index()
        {
            var model = await _context.Ogrenciler.ToListAsync();
            return View(model);
        }
        public async Task<IActionResult> Guncelle(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var model = await _context.Ogrenciler.FirstOrDefaultAsync(x=>x.OgrenciId == id);
            if(model == null)
            {
                return NotFound();
            }
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Guncelle(Ogrenci model)
        {
            if(ModelState.IsValid)
            {
                _context.Ogrenciler.Update(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
            
        }

        public async Task<IActionResult> Sil(int? id)
        {
            if(id== null)
            {
                return NotFound();
            }
            var model = await _context.Ogrenciler.FirstOrDefaultAsync(x=>x.OgrenciId == id);
            if(model == null)
            {
                return NotFound();
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Sil([FromForm]int OgrenciId)
        {
            var model = await _context.Ogrenciler.FirstOrDefaultAsync(x=>x.OgrenciId == OgrenciId);
            if(model == null)
            {
                return NotFound();
            }
            _context.Ogrenciler.Remove(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

MVC2/CourseApp3/Views/Ogrenci/Create.cshtml
@{
    ViewData["Title"] = "Öğrenci Ekle";
}
@model Ogrenci

<div class="card m-auto">
    <div class="card-header">
        <h5>Öğrenci Ekle</h5>
    </div>
    <div class="card-body bg-white">
        <form asp-asp-controller="Ogrenci" asp-action="Create" method="post">
            <div class="mb-3">
                <label asp-for="OgrenciAd" class="form-label">Öğrenci Ad</label>
                <input type="text" asp-for="OgrenciAd" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="OgrenciSoyad" class="form-label">Öğrenci Soyad</label>
                <input type="text" asp-for="OgrenciSoyad" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label">Email</label>
                <input type="text" asp-for="Email" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Telefon" class="form-label">Telefon</label>
                <input type="text" asp-for="Telefon" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Kaydet</button>
        </form>
    </div>
</div>

MVC2/CourseApp3/Views/Ogrenci/Guncelle.cshtml
@{
    ViewData["Title"] = "Öğrenci Güncelle";
}
@model Ogrenci

<div class="card m-auto">
    <div class="card-header">
        <h5>Öğrenci Güncelle</h5>
    </div>
    <div class="card-body bg-white">
        <form asp-asp-controller="Ogrenci" asp-action="Guncelle" method="post">
            <input type="hidden" name="OgrenciId" value="@Model.OgrenciId">
            <div class="mb-3">
                <label asp-for="OgrenciAd" class="form-label">Öğrenci Ad</label>
                <input type="text" asp-for="OgrenciAd" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="OgrenciSoyad" class="form-label">Öğrenci Soyad</label>
                <input type="text" asp-for="OgrenciSoyad" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label">Email</label>
                <input type="text" asp-for="Email" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Telefon" class="form-label">Telefon</label>
                <input type="text" asp-for="Telefon" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Kaydet</button>
        </form>
    </div>
</div>

MVC2/CourseApp3/Views/Ogrenci/Index.cshtml
@model IEnumerable<Ogrenci>
<h2>
    Öğrenci Listesi
</h2>
<a href="/Ogrenci/Create" class="btn btn-primary">Öğrenci Ekle</a>
<hr>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(x=>x.OgrenciId)</th>
            <th>Öğrenci Ad</th>
            <th>Öğrenci Soyad</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var ogrenci in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem=>ogrenci.OgrenciId)</td>
                <td>@ogrenci.OgrenciAd</td>
                <td>@ogrenci.OgrenciSoyad</td>
                <td>
                    <a asp-controller="Ogrenci" asp-action="Guncelle" asp-route-id="@ogrenci.OgrenciId" class="btn btn-primary btn-sm">Güncelle</a>
                    <a href="/Ogrenci/Sil/@ogrenci.OgrenciId" class="btn btn-danger btn-sm">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MVC2/CourseApp3/Views/Ogrenci/Sil.cshtml
@model Ogrenci

<p>
    <b>@Model.OgrenciAd @Model.OgrenciSoyad </b> isimli öğrenciyi silmek istiyor musunuz?
</p>
<form asp-action="Sil" method="post">
    <input type="hidden" name="OgrenciId" value="@Model.OgrenciId">
    <button type="submit" class="btn btn-primary">Evet</button>
    <a asp-action="Index" class="btn btn-danger">Hayır</a>
</form>