MovieAppDinamik/MovieApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;
using MovieApp.Models;

namespace MovieApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly MovieContext _context;
        public HomeController(MovieContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = new HomePageViewModel { PopulerMovies = _context.Movies.ToList() };
            return View(model);
        }

        public IActionResult About()
        {
            //var turListesi = new List<Genre>()
            //{
            //    new Genre{Name="Macera"},
            //    new Genre{Name="Komedi"},
            //    new Genre{Name="Korku"},
            //    new Genre{Name="Animasyon"},
            //};
            return View();
        }

        
    }
}

MovieAppDinamik/MovieApp/ViewComponents/GenresViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;
using MovieApp.Models;

namespace MovieApp.ViewComponents
{
    public class GenresViewComponent:ViewComponent
    {
        private readonly MovieContext _context;
        public GenresViewComponent(MovieContext context)
        {
            _context = context;
        }
        public IViewComponentResult Invoke()
        {
            //var turListesi = new List<Genre>()
            //{
            //    new Genre{Name="Macera"},
            //    new Genre{Name="Komedi"},
            //    new Genre{Name="Korku"},
            //    new Genre{Name="Animasyon"},
            //};
            ViewBag.SelectedGenreId = RouteData.Values["id"];

            //return View(GenreRepository.GetGenres);
            return View(_context.Genres.ToList());
        }
    }
}

MovieAppDinamik/MovieApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model HomePageViewModel
@section main_header{ 

@await Html.PartialAsync("_main_header")
}

<div class="container py-5">
    <h2>Film Listesi</h2>
    @foreach(var movie in Model.PopulerMovies)
      {
         @await Html.PartialAsync("_movie", movie)
      }
</div>

MovieAppDinamik/MovieApp/Views/Home/about.cshtml
<p>
    Home / About
</p>
@section menu
{
    @*@await Html.PartialAsync("_menu", Model)*@
    @await Component.InvokeAsync("Genres")
}